name: TheLastArcher
author: joaoemilio
version: 1.0.0
main: br.com.minegames.arqueiro.GameController
depend: [TheCraftCloud-Client,TheCraftCloud-Core,TheCraftCloud-Plugin]
commands:
  jogar:
  sair:
  iniciar:
  tparena:  
  fwk: